### PR TITLE
Calm cilantro: badge component

### PR DESCRIPTION
**Pull request by modernserf**
http://calm-cilantro.glitch.me/#StoryBadge

Cross-browser rendering gets real iffy at these small sizes -- i think Chrome rounds ems to the nearest "full" pixel while Safari will fit to retina pixels:

Safari
Screen Shot 2019-07-30 at 4 30 32 PM

Chrome
Screen Shot 2019-07-30 at 4 30 37 PM

### CODE REVIEW

**Comment by ehmorris** [comment]
I recently made this change for narrow sidebars: https://github.com/FogCreek/Glitch-Editor/pull/74#issuecomment-514724375

Maybe this could be a badge variant like "mini".

**Comment by modernserf** [comment]
updated with collapsed badges

**Comment by sheridanvk** [comment]
Trying to test this via createRemoteComponent in the editor and short-koala.glitch.me, but getting this error:
```
module.js:578 Uncaught TypeError: styled__default.css is not a function
    at module.js:578
    at window.defineSharedComponent (module.js:649)
    at module.js:3
    at module.js:5
(anonymous) @ module.js:578
window.defineSharedComponent @ module.js:649
(anonymous) @ module.js:3
(anonymous) @ module.js:5
module.js:672 Uncaught (in promise) TypeError: Cannot read property 'Badge' of undefined
    at eval (module.js:672)
```

**Comment by sheridanvk** [comment]
We also have a grey badge variant in the editor, which looks like this (used when the container is not running). Please could you add that? I guess it could be named something like "disabled" or "inactive"?
Screenshot 2019-08-14 at 10 05 22 AM

**Comment by modernserf** [comment]
that badge fails WCAG contrast; the lightest you can get is basically indistinguishable from the 'normal' color

**Comment by modernserf** [comment]
updated

**Comment by sheridanvk** [comment]
> that badge fails WCAG contrast; the lightest you can get is basically indistinguishable from the 'normal' color

ok! thanks for catching that - we still need this badge though, so perhaps we can make the grey darker to the point where it doesn't fail contrast any more? @ehmorris how about we use our text-on-secondary-background = #636363 colour for that?

Screenshot 2019-08-15 at 10 38 27 AM

**Comment by sheridanvk** [comment]
Oh ok, I see you added Inactive and there's a Normal badge for the #636363 colour. Looks good, thanks.

**Comment by keithk** [comment]
:rocket: PR was released in [`v0.19.0`](https://github.com/glitchdotcom/shared-components/releases/tag/v0.19.0) :rocket:

**Pull request merged**
