### PR TITLE
Moved All Emoji to Shared Component Asset Library

### PR DESCRIPTION
**Pull request by ttseng**
Rather than reference emoji assets on `community`, emojis now all live in the shared component library

image

### CODE REVIEW

**Comment by modernserf** [comment]
can you update this to include the handshake and party emoji that were just added?

**Comment by ttseng** [comment]
updated to include latest set of emoji (television + telephone)
image

**Comment by ttseng** [comment]
@modernserf do you mind reviewing this?  (I'd like to add a the Glitch icon to the emoji set in a separate PR)

**Comment by keithk** [comment]
:rocket: PR was released in [`v0.19.0`](https://github.com/glitchdotcom/shared-components/releases/tag/v0.19.0) :rocket:

**Pull request merged**
