### PR TITLE
Run the styled components babel plugin, replace sucrase with babel

### PR DESCRIPTION
**Pull request by GregWeil**
The styled components plugin doesn't work if anything else has transformed the code before it, so it needs to run in the shared components build step.

Additionally, the plugin's latest version doesn't transpile our code properly, so I've pinned it to the previous version.

I opted to remove sucrase in favor of running everything through babel, but it still works with sucrase handling the jsx transform if that's preferred.

### CODE REVIEW

**Comment by GregWeil** [comment]
https://quixotic-rocket.glitch.me/ is a working community site with not hydration errors

**Comment by modernserf** [comment]
can you bump the version and update the changelog on this?

**Comment by GregWeil** [comment]
Is anything else needed for this pr?

**Comment by keithk** [comment]
:rocket: PR was released in [`v0.19.0`](https://github.com/glitchdotcom/shared-components/releases/tag/v0.19.0) :rocket:

**Pull request merged**
