### PR TITLE
Fallacious garment: disabled button styling

### PR DESCRIPTION
**Pull request by whimsicallyson**
was PR #38

### CODE REVIEW

**Comment by whimsicallyson** [comment]
@modernserf anything I need to do after merging?

**Comment by modernserf** [comment]
after merging:
- pull the changes into the `shared-components` project
- run `sh/publish.sh shared-components --production` from your local instance of shared components

**Comment by whimsicallyson** [comment]
done!

**Comment by keithk** [comment]
:rocket: PR was released in [`v0.19.0`](https://github.com/glitchdotcom/shared-components/releases/tag/v0.19.0) :rocket:

**Pull request merged**
