### PR TITLE
🍋🚊 Checkpoint

### PR DESCRIPTION
**Pull request by whimsicallyson**
adds a z-index to overlays (already did this with popovers)

### CODE REVIEW

**Comment by sarahzinger** [comment]
why remove the variable? it works in shared-components.glitch.me right?

**Comment by whimsicallyson** [comment]
@sarahzinger it only works by accident...
Screen Shot 2019-11-05 at 2 57 57 PM

**Comment by sarahzinger** [comment]
gotcha, is there a way to make it work in the theme? https://github.com/FogCreek/shared-components/blob/bce898e28eb64e596387bb44a169193594bbdcd8/lib/themes.js#L17

maybe it has to be a string or something like that?

**Comment by whimsicallyson** [comment]
good catch!

**Comment by sarahzinger** [comment]
jk we don't use overlays or notifications in community so there'd be nothing to test

**Comment by keithk** [comment]
:rocket: PR was released in [`v0.19.0`](https://github.com/glitchdotcom/shared-components/releases/tag/v0.19.0) :rocket:

**Pull request merged**
