### PR TITLE
Stingy argument: TextInput & TextArea components

### PR DESCRIPTION
**Pull request by modernserf**
http://stingy-argument.glitch.me/#StoryTextInput

- are there any other visual styles of text inputs that I'm missing here?
- are there cases where TextArea _shouldn't_ auto-size? or should that be built in?

### CODE REVIEW

**Comment by ehmorris** [comment]
These look about right to me. I think autosizing textareas should be the default, but I noticed that the autosizing textarea in this example still becomes scrollable:

Screencast

**Comment by modernserf** [comment]
Yeah, my implementation was pretty hacky; i was trying to avoid actually pulling in that dependency but I guess there's no reason to avoid it.

**Comment by modernserf** [comment]
Updated with autosizing on by default.

**Comment by ehmorris** [comment]
I think the transition style should be removed from the autosized textareas. Here's a textarea as it is now vs. one w/o a transition:

| w/ transition | w/o transition |
| -- | -- |
| Screencast | Screencast2 |

**Comment by keithk** [comment]
:rocket: PR was released in [`v0.19.0`](https://github.com/glitchdotcom/shared-components/releases/tag/v0.19.0) :rocket:

**Pull request merged**
